#!/bin/bash -p
case $1 in
    'start')
	clear
	cd /home/emulador;
	date > /var/www/html/painel/logs/login.txt &
	date > /var/www/html/painel/logs/char.txt &
	date > /var/www/html/painel/logs/map.txt &
	sh ./login-server.sh start >> /var/www/html/painel/logs/login.txt &
	sh ./char-server.sh start >> /var/www/html/painel/logs/char.txt &
	sh ./map-server.sh start >> /var/www/html/painel/logs/map.txt &
;;
    'stop')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
;;
    'restart')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
	cd /home/emulador;
	date > /var/www/html/painel/logs/login.txt &
	date > /var/www/html/painel/logs/char.txt &
	date > /var/www/html/painel/logs/map.txt &
	sh ./login-server.sh start >> /var/www/html/painel/logs/login.txt &
	sh ./char-server.sh start >> /var/www/html/painel/logs/char.txt &
	sh ./map-server.sh start >> /var/www/html/painel/logs/map.txt &
;;
	'compilar')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
	date > /var/www/html/painel/logs/recompilar.txt &
	cd /home/emulador;
	./configure >> /var/www/html/painel/logs/recompilar.txt &
	make clean >> /var/www/html/painel/logs/recompilar.txt &
	make sql >> /var/www/html/painel/logs/recompilar.txt &
;;
esac