#!/bin/bash -p
case $1 in
	'atualizar')
	clear
	date > /var/www/html/painel/logs/atualizar.txt &
	svn update /home/emulador >> /var/www/html/painel/logs/atualizar.txt &
	svn update /var/www/html/phpMyAdmin >> /var/www/html/painel/logs/atualizar.txt &
	svn update /var/www/html/painel >> /var/www/html/painel/logs/atualizar.txt &
	svn update /usr/bin >> /var/www/html/painel/logs/atualizar.txt &
;;
    'start')
	clear
	cd /home/emulador;
	date > /var/www/html/painel/logs/login.txt &
	date > /var/www/html/painel/logs/char.txt &
	date > /var/www/html/painel/logs/map.txt &
	sh ./login-server.sh start >> /var/www/html/painel/logs/login.txt &
	sh ./char-server.sh start >> /var/www/html/painel/logs/char.txt &
	sh ./map-server.sh start >> /var/www/html/painel/logs/map.txt &
;;
    'stop')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
;;
    'restart')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
	cd /home/emulador;
	date > /var/www/html/painel/logs/login.txt &
	date > /var/www/html/painel/logs/char.txt &
	date > /var/www/html/painel/logs/map.txt &
	sh ./login-server.sh start >> /var/www/html/painel/logs/login.txt &
	sh ./char-server.sh start >> /var/www/html/painel/logs/char.txt &
	sh ./map-server.sh start >> /var/www/html/painel/logs/map.txt &
;;
	'recompilar')
	clear
	ps ax | grep -E "login-server|char-server|map-server" | awk '{print $1}' | xargs kill
	date > /var/www/html/painel/logs/recompilar.txt &
	cd /home/emulador;
	./configure >> /var/www/html/painel/logs/recompilar.txt &
	make clean >> /var/www/html/painel/logs/recompilar.txt &
	make sql >> /var/www/html/painel/logs/recompilar.txt &
;;
esac