#!/bin/bash
case $1 in
    'start')
	clear
	cd /home/emulador;
    exec ./login-server > /var/www/html/painel/logs/login.txt &
    exec ./char-server > /var/www/html/painel/logs/char.txt &
    exec ./map-server > /var/www/html/painel/logs/map.txt &
;;
    'stop')
	clear
	killall login-server
	killall map-server
	killall char-server
;;
    'restart')
	clear
	killall login-server
	killall map-server
	killall char-server
	clear
	cd /home/emulador;
    exec ./login-server > /var/www/html/painel/logs/login.txt &
    exec ./char-server > /var/www/html/painel/logs/char.txt &
    exec ./map-server > /var/www/html/painel/logs/map.txt &
;;
	'compilar')
	clear
	cd /home/emulador;
	sh ./configure
	make clean
	make sql
;;
esac